seed: 2222
clean: 2
debug: false
train: true
result: sagittalcenters
load_directory: null
mode: valid
directories:
  relative_directory: /data/phalendj/kaggle/rsna2024
  image_directory: train_images
dataset:
  name: SegmentationPredictedCenterDataset
  image_size:
  - 512
  - 512
  series_description: Sagittal T2/STIR
  conditions:
  - Spinal Canal Stenosis
  channels: 15
  aug_size: 0.1
  center_file: /data/phalendj/kaggle/rsna2024/train_label_coordinates.csv
  augmentations:
    prob: 0.75
    normalize: true
    hflip: false
    contrast: true
    blur: true
    blur_limit: 9
    noise: true
    downscale: true
    distort: false
    rotate: false
    crop:
      use: false
      size: 512
    channel_shuffle: false
    sharpen: false
loss:
  name: HeatmapLoss
  patch_size: 512
  h_scale: 8.0
model:
  name: unet
  encodername: timm-efficientnet-b2
  model_name: densenet121
  channels: 15
  unet_classes: 5
  nclasses: 15
  patch_size: 512
optimization:
  optimizer: AdamW
  learning_rate: 0.0002
  weight_decay: 0.01
  scheduler: MultiStepLR
  milestones:
  - 15
  - 25
  gamma: 0.3
training:
  use_folds:
  - 0
  - 1
  - 2
  - 3
  - 4
  use_amp: true
  epochs: 30
  batch_size: 24
  grad_acc: 1
  early_stopping: 5
  workers: 12
